In [11]:
import tensorflow as tf
import os
tf.__version__

'2.5.0'

In [9]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5])
for el in dataset:
    print(el)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)


In [13]:
DIRECTORY_URL = 'https://storage.googleapis.com/download.tensorflow.org/data/illiad/'
FILE_NAMES = ['cowper.txt', 'derby.txt', 'butler.txt']
for name in FILE_NAMES:
  text_dir = tf.keras.utils.get_file(name, origin=DIRECTORY_URL+name)
  print(text_dir)   

parent_dir = os.path.dirname(text_dir)

parent_dir


/Users/zhanghaisheng/.keras/datasets/cowper.txt
/Users/zhanghaisheng/.keras/datasets/derby.txt
/Users/zhanghaisheng/.keras/datasets/butler.txt


'/Users/zhanghaisheng/.keras/datasets'

In [17]:
def labeler(example, index):
  return example, tf.cast(index, tf.int64)


labeled_data_sets = []

for i, file_name in enumerate(FILE_NAMES):
  lines_dataset = tf.data.TextLineDataset(os.path.join(parent_dir, file_name))
  print(lines_dataset)
  labeled_dataset = lines_dataset.map(lambda ex: labeler(ex, i))
  print(labeled_dataset)
  labeled_data_sets.append(labeled_dataset)

<TextLineDatasetV2 shapes: (), types: tf.string>
<MapDataset shapes: ((), ()), types: (tf.string, tf.int64)>
<TextLineDatasetV2 shapes: (), types: tf.string>
<MapDataset shapes: ((), ()), types: (tf.string, tf.int64)>
<TextLineDatasetV2 shapes: (), types: tf.string>
<MapDataset shapes: ((), ()), types: (tf.string, tf.int64)>


In [18]:
BUFFER_SIZE = 50000
BATCH_SIZE = 64
TAKE_SIZE = 5000

all_labeled_data = labeled_data_sets[0]
for labeled_dataset in labeled_data_sets[1:]:
  all_labeled_data = all_labeled_data.concatenate(labeled_dataset)

all_labeled_data = all_labeled_data.shuffle(
    BUFFER_SIZE, reshuffle_each_iteration=False)

for ex in all_labeled_data.take(5):
  print(ex)

2021-07-14 15:32:29.510318: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)


(<tf.Tensor: shape=(), dtype=string, numpy=b'In this disastrous day, nor thus permit'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'Through all her base and to her topmost peak'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'While with sharp steel Achilles from the bone'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'Once reach thee, the Olympian Powers combined'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=string, numpy=b'That speak, and boldly. By the son of Jove,'>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
